package com.enviouse.progressivestages.server.migration;

import com.enviouse.progressivestages.common.api.StageId;
import com.enviouse.progressivestages.server.loader.StageFileParser;
import com.enviouse.progressivestages.server.loader.StagePackageDiscovery;
import com.enviouse.progressivestages.server.loader.StagePackageParser;

import java.io.IOException;
import java.lang.reflect.Method;
import java.nio.charset.StandardCharsets;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.security.MessageDigest;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

public final class LegacyMigrationService {
    private static final Set<String> IDENTITY = Set.of("stage", "display", "dependencies", "metadata");
    private static final Set<String> PROGRESSION = Set.of("triggers", "grants", "revoke", "revokes", "duration",
        "cost", "unlock", "rewards", "challenges", "sequences", "variables", "formulas", "states",
        "transitions", "actions", "templates", "profiles", "currencies", "counters");
    private static final DateTimeFormatter ID_FORMAT = DateTimeFormatter.ofPattern("yyyyMMddHHmmssSSS")
        .withLocale(Locale.ROOT).withZone(ZoneOffset.UTC);

    private final Path stagesRoot;
    private final Path backupRoot;

    public LegacyMigrationService(Path stagesRoot) {
        this.stagesRoot = stagesRoot.toAbsolutePath().normalize();
        this.backupRoot = this.stagesRoot.resolve(".migration-backups");
    }

    public List<MigrationScanEntry> scan() {
        StagePackageDiscovery.DiscoveryResult discovery = StagePackageDiscovery.discover(stagesRoot);
        List<MigrationScanEntry> results = new ArrayList<>();
        for (Path source : discovery.legacyFiles()) {
            StageFileParser.ParseResult parsed = StageFileParser.parseWithErrors(source);
            List<String> errors = parsed.isSuccess() ? List.of() : List.of(parsed.getErrorMessage());
            results.add(new MigrationScanEntry(parsed.isSuccess() ? parsed.getStageDefinition().getId() : null,
                source, checksum(source), parsed.isSuccess(), List.of(), errors));
        }
        return List.copyOf(results);
    }

    public MigrationPlan plan(Path source) {
        Path safeSource = containedFile(source);
        StageFileParser.ParseResult parsed = StageFileParser.parseWithErrors(safeSource);
        if (!parsed.isSuccess()) throw new IllegalArgumentException(parsed.getErrorMessage());
        StageId stage = parsed.getStageDefinition().getId();
        String content;
        try { content = Files.readString(safeSource); }
        catch (IOException error) { throw new IllegalArgumentException("Could not read the legacy stage. " + error.getMessage(), error); }
        Split split = split(content);
        Map<String, String> generated = new LinkedHashMap<>();
        generated.put("stage.toml", "# Generated by the ProgressiveStages schema 4 migration.\n[schema]\nversion = 4\n\n" + split.identity());
        if (!split.rules().isBlank()) generated.put("rules.toml", split.rules());
        if (!split.progression().isBlank()) generated.put("progression.toml", split.progression());
        validateGenerated(stage, generated);
        List<String> mappings = new ArrayList<>();
        split.sections().forEach((section, file) -> mappings.add(section + " to " + file));
        return new MigrationPlan(stage, safeSource, stagesRoot.resolve(safeDirectory(stage)), checksum(safeSource),
            generated, mappings, List.of("The untouched original is retained in a checksummed backup"),
            semanticFingerprint(parsed.getStageDefinition()));
    }

    public MigrationResult write(MigrationPlan plan) {
        if (!checksum(plan.source()).equals(plan.sourceChecksum())) {
            return failure("source_changed", "The legacy source changed after the migration plan was created");
        }
        if (Files.exists(plan.targetDirectory())) return failure("target_exists", "The target package already exists");
        String migrationId = ID_FORMAT.format(Instant.now()) + "_" + safeDirectory(plan.stage());
        Path backup = backupRoot.resolve(migrationId).normalize();
        Path temporary = stagesRoot.resolve(".migration-temp-" + migrationId).normalize();
        try {
            Files.createDirectories(backup);
            Files.copy(plan.source(), backup.resolve("original.toml"));
            Files.writeString(backup.resolve("original.sha256"), plan.sourceChecksum() + "\n", StandardCharsets.UTF_8);
            Files.writeString(backup.resolve("target.txt"), stagesRoot.relativize(plan.targetDirectory()).toString() + "\n", StandardCharsets.UTF_8);
            Files.writeString(backup.resolve("source.txt"), stagesRoot.relativize(plan.source()).toString() + "\n", StandardCharsets.UTF_8);
            Files.createDirectories(temporary);
            for (Map.Entry<String, String> file : plan.generatedFiles().entrySet()) {
                Files.writeString(temporary.resolve(file.getKey()), file.getValue(), StandardCharsets.UTF_8);
            }
            validateGenerated(plan.stage(), plan.generatedFiles());
            move(temporary, plan.targetDirectory());
            Files.delete(plan.source());
            if (!verify(plan, plan.targetDirectory())) throw new IllegalStateException("Semantic verification failed after writing");
            List<Path> written = plan.generatedFiles().keySet().stream().map(plan.targetDirectory()::resolve).toList();
            Files.writeString(backup.resolve("committed.txt"), "true\n", StandardCharsets.UTF_8);
            return new MigrationResult(true, migrationId, backup, written, "ok", "Migration completed and verified");
        } catch (Exception error) {
            try {
                deleteTree(temporary);
                deleteTree(plan.targetDirectory());
                if (!Files.exists(plan.source()) && Files.isRegularFile(backup.resolve("original.toml"))) {
                    Files.copy(backup.resolve("original.toml"), plan.source());
                }
            } catch (IOException ignored) {}
            return new MigrationResult(false, migrationId, backup, List.of(), "write_failed", error.getMessage());
        }
    }

    public boolean verify(MigrationPlan plan, Path packageDirectory) {
        try {
            var source = StagePackageParser.inspect(stagesRoot, packageDirectory);
            var parsed = StagePackageParser.parse(source);
            return parsed.isSuccess() && parsed.getStageDefinition().getId().equals(plan.stage())
                && semanticFingerprint(parsed.getStageDefinition()).equals(plan.semanticFingerprint());
        } catch (IOException | RuntimeException error) {
            return false;
        }
    }

    public MigrationResult rollback(String migrationId) {
        if (migrationId == null || !migrationId.matches("[a-zA-Z0-9_.]+")) return failure("invalid_id", "Invalid migration id");
        Path backup = backupRoot.resolve(migrationId).normalize();
        if (!backup.startsWith(backupRoot) || !Files.isDirectory(backup)) return failure("missing_backup", "Migration backup was not found");
        try {
            String expected = Files.readString(backup.resolve("original.sha256")).trim();
            if (!checksum(backup.resolve("original.toml")).equals(expected)) return failure("checksum_mismatch", "The migration backup checksum does not match");
            Path source = stagesRoot.resolve(Files.readString(backup.resolve("source.txt")).trim()).normalize();
            Path target = stagesRoot.resolve(Files.readString(backup.resolve("target.txt")).trim()).normalize();
            if (!source.startsWith(stagesRoot) || !target.startsWith(stagesRoot)) return failure("unsafe_path", "The migration backup contains an unsafe path");
            deleteTree(target);
            Files.createDirectories(source.getParent());
            Files.copy(backup.resolve("original.toml"), source, StandardCopyOption.REPLACE_EXISTING);
            return new MigrationResult(true, migrationId, backup, List.of(source), "ok", "Migration rollback completed");
        } catch (IOException error) {
            return new MigrationResult(false, migrationId, backup, List.of(), "rollback_failed", error.getMessage());
        }
    }

    private void validateGenerated(StageId expected, Map<String, String> generated) {
        var parsed = StagePackageParser.parseContents("migration", "stage.toml", generated.get("stage.toml"),
            "rules.toml", generated.get("rules.toml"), "progression.toml", generated.get("progression.toml"));
        if (!parsed.isSuccess()) throw new IllegalArgumentException(parsed.getErrorMessage());
        if (!parsed.getStageDefinition().getId().equals(expected)) throw new IllegalArgumentException("Generated package changed the stage id");
    }

    private Path containedFile(Path source) {
        Path normalized = source.toAbsolutePath().normalize();
        if (!normalized.startsWith(stagesRoot) || !Files.isRegularFile(normalized)) {
            throw new IllegalArgumentException("Migration source must be a legacy file inside the stages folder");
        }
        return normalized;
    }

    private static Split split(String content) {
        Map<String, StringBuilder> files = new LinkedHashMap<>();
        files.put("stage.toml", new StringBuilder());
        files.put("rules.toml", new StringBuilder());
        files.put("progression.toml", new StringBuilder());
        Map<String, String> mappings = new LinkedHashMap<>();
        String destination = "stage.toml";
        List<String> pending = new ArrayList<>();
        for (String line : content.split("\\R", -1)) {
            String trimmed = line.trim();
            if (trimmed.startsWith("[") && trimmed.endsWith("]")) {
                String root = sectionRoot(trimmed);
                destination = IDENTITY.contains(root) ? "stage.toml" : PROGRESSION.contains(root)
                    ? "progression.toml" : "rules.toml";
                mappings.put(trimmed, destination);
                for (String value : pending) files.get(destination).append(value).append('\n');
                pending.clear();
                files.get(destination).append(line).append('\n');
            } else if (trimmed.isEmpty() || trimmed.startsWith("#")) {
                pending.add(line);
            } else {
                for (String value : pending) files.get(destination).append(value).append('\n');
                pending.clear();
                files.get(destination).append(line).append('\n');
            }
        }
        for (String value : pending) files.get(destination).append(value).append('\n');
        return new Split(files.get("stage.toml").toString().strip() + "\n",
            files.get("rules.toml").toString().strip() + "\n",
            files.get("progression.toml").toString().strip() + "\n", Map.copyOf(mappings));
    }

    private static String sectionRoot(String header) {
        String value = header.replace("[", "").replace("]", "").trim();
        int dot = value.indexOf('.');
        return (dot < 0 ? value : value.substring(0, dot)).toLowerCase(Locale.ROOT);
    }

    private static String semanticFingerprint(Object definition) {
        return checksum(semanticDocument(definition).getBytes(StandardCharsets.UTF_8));
    }

    static String semanticDocument(Object definition) {
        StringBuilder value = new StringBuilder();
        Method[] methods = definition.getClass().getMethods();
        java.util.Arrays.stream(methods).filter(method -> method.getParameterCount() == 0)
            .filter(method -> (method.getName().startsWith("get") || method.getName().startsWith("is") || method.getName().startsWith("has")))
            .filter(method -> !method.getName().equals("getClass") && !method.getName().equals("getProvenance")
                && !method.getName().equals("getSchemaVersion") && !method.getName().equals("hashCode"))
            .sorted(Comparator.comparing(Method::getName)).forEach(method -> {
                try { value.append(method.getName()).append('=').append(normalizeValue(method.invoke(definition))).append('\n'); }
                catch (ReflectiveOperationException error) { throw new IllegalStateException(error); }
            });
        return value.toString();
    }

    private static String normalizeValue(Object value) {
        return normalizeValue(value, java.util.Collections.newSetFromMap(new java.util.IdentityHashMap<>()));
    }

    private static String normalizeValue(Object value, Set<Object> visiting) {
        if (value == null) return "null";
        if (value instanceof CharSequence || value instanceof Number || value instanceof Boolean
                || value instanceof Enum<?> || value instanceof net.minecraft.resources.ResourceLocation
                || value instanceof com.enviouse.progressivestages.common.api.StageId) return String.valueOf(value);
        if (value instanceof java.util.Optional<?> optional) return optional.map(item -> normalizeValue(item, visiting)).orElse("empty");
        if (value instanceof Map<?, ?> map) return map.entrySet().stream()
            .sorted(Comparator.comparing(entry -> String.valueOf(entry.getKey())))
            .map(entry -> normalizeValue(entry.getKey(), visiting) + "=" + normalizeValue(entry.getValue(), visiting)).toList().toString();
        if (value instanceof Set<?> set) return set.stream().map(item -> normalizeValue(item, visiting)).sorted().toList().toString();
        if (value instanceof Iterable<?> values) {
            List<String> normalized = new ArrayList<>();
            values.forEach(item -> normalized.add(normalizeValue(item, visiting)));
            return normalized.toString();
        }
        if (value.getClass().isArray()) {
            List<String> normalized = new ArrayList<>();
            for (int index = 0; index < java.lang.reflect.Array.getLength(value); index++) {
                normalized.add(normalizeValue(java.lang.reflect.Array.get(value, index), visiting));
            }
            return normalized.toString();
        }
        if (!visiting.add(value)) return "cycle";
        try {
            if (value.getClass().getName().startsWith("com.enviouse.progressivestages")) {
                List<java.lang.reflect.Field> fields = new ArrayList<>();
                for (Class<?> type = value.getClass(); type != null && type != Object.class; type = type.getSuperclass()) {
                    for (java.lang.reflect.Field field : type.getDeclaredFields()) {
                        if (!java.lang.reflect.Modifier.isStatic(field.getModifiers())
                                && !field.getName().equals("provenance") && !field.getName().equals("schemaVersion")) fields.add(field);
                    }
                }
                fields.sort(Comparator.comparing(java.lang.reflect.Field::getName));
                if (!fields.isEmpty()) return value.getClass().getName() + fields.stream().map(field -> {
                    try { field.setAccessible(true); return field.getName() + "=" + normalizeValue(field.get(value), visiting); }
                    catch (ReflectiveOperationException error) { throw new IllegalStateException(error); }
                }).toList();
            }
            List<String> properties = java.util.Arrays.stream(value.getClass().getMethods())
                .filter(method -> method.getParameterCount() == 0)
                .filter(method -> method.getName().startsWith("get") || method.getName().startsWith("is")
                    || method.getName().startsWith("has"))
                .filter(method -> !method.getName().equals("getClass") && !method.getName().equals("getProvenance")
                    && !method.getName().equals("getSchemaVersion") && !method.getName().equals("hashCode"))
                .sorted(Comparator.comparing(Method::getName)).map(method -> {
                    try { return method.getName() + "=" + normalizeValue(method.invoke(value), visiting); }
                    catch (ReflectiveOperationException error) { throw new IllegalStateException(error); }
                }).toList();
            if (!properties.isEmpty()) return value.getClass().getName() + properties;
            if (value.getClass().isRecord()) {
                return value.getClass().getName() + java.util.Arrays.stream(value.getClass().getRecordComponents())
                    .map(component -> {
                        try { return component.getName() + "=" + normalizeValue(component.getAccessor().invoke(value), visiting); }
                        catch (ReflectiveOperationException error) { throw new IllegalStateException(error); }
                    }).toList();
            }
            return value.getClass().getName();
        } finally {
            visiting.remove(value);
        }
    }

    private static String safeDirectory(StageId stage) {
        return stage.toString().replace(':', '_').replace('/', '_');
    }

    private static String checksum(Path file) {
        try { return checksum(Files.readAllBytes(file)); }
        catch (IOException error) { return ""; }
    }

    private static String checksum(byte[] bytes) {
        try { return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes)); }
        catch (Exception impossible) { throw new IllegalStateException(impossible); }
    }

    private static void move(Path source, Path target) throws IOException {
        try { Files.move(source, target, StandardCopyOption.ATOMIC_MOVE); }
        catch (AtomicMoveNotSupportedException error) { Files.move(source, target); }
    }

    private static void deleteTree(Path root) throws IOException {
        if (!Files.exists(root)) return;
        try (var paths = Files.walk(root)) {
            for (Path path : paths.sorted(Comparator.reverseOrder()).toList()) Files.deleteIfExists(path);
        }
    }

    private static MigrationResult failure(String code, String explanation) {
        return new MigrationResult(false, "", null, List.of(), code, explanation);
    }

    private record Split(String identity, String rules, String progression, Map<String, String> sections) {}
}
